export const TYPES = {
    GET_PROFESIONALES: "GET_PROFESIONALES",
    GET_PROFESIONAL: "GET_PROFESIONAL",
    ADD_PROFESIONAL: "ADD_PROFESIONAL",
    DELETE_PROFESIONAL: "DELETE_PROFESIONAL",
    UPDATE_PROFESIONAL: "UPDATE_PROFESIONAL",
    
}